### ISSUE TITLE
Node 12 SyntaxError

### ISSUE THREAD

**Issue by MatusBoa** [reviewdog/action-stylelint#120]
Hello, 

i tried to run this action on self-hosted ARM64 runner with Node 12 installed.

After run, got this error 

![image](https://github.com/reviewdog/action-stylelint/assets/8343385/82a1e871-b772-4a24-b491-af312100d2b5)

I read something about optional chaining and discovered, it is not supported in node 12.

Are there any plans to support node 12 in this action ?

Thanks.

**Comment by shogo82148** [comment]
No. Node.js 12 has already ended its life.

https://endoflife.date/nodejs

<img width="752" alt="image" src="https://github.com/reviewdog/action-stylelint/assets/1157344/41aa525b-a805-452e-b91e-06bbb7cb49b8">

Please use Node.js 18 or 20.
