### ISSUE TITLE
support --ignore-path option

### ISSUE THREAD

**Issue by yshrsmz** [reviewdog/action-stylelint#28]
https://github.com/stylelint/stylelint/blob/master/docs/user-guide/ignore-code.md#files-entirely

It would be great if this action supports `--ignore-path` option as well. stylelint by default checks `.stylelintignore`, but I'd like to use `.gitignore` instead.

**Comment by haya14busa** [comment]
PR is welcome :)

**Comment by bert-mccutchen** [comment]
Fixed by #104
